answers = [
    "Throwing grapes at a man until he loses touch with reality.",
    "A stray pube.",
    "Facebook.",
    "Pac-Man uncontrollably guzzling cum.",
    "An Oedipus complex.",
    "Scientology.",
    "My fat daughter.",
    "Having big dreams but no realistic way to achieve them.",
    "A time travel paradox.",
    "Lactation.",
    "Dick fingers.",
    "Dying.",
    "My good bra.",
    "Me time.",
    "Seeing my father cry.",
    "Hot people.",
    "Dead babies.",
    "Not reciprocating oral sex.",
    "A bleached asshole.",
    "Flesh-eating bacteria.",
    "Itchy pussy.",
    "Foreskin.",
    "How far I can get my own penis up my butt.",
    "World peace.",
    "Expecting a burp and vomiting on the floor.",
    "Kamikaze pilots.",
    "Being rich.",
    "Shapeshifters.",
    "Breaking out into song and dance.",
    "Pretending to care.",
    "Waiting till marriage.",
    "The wifi password.",
    "Being a woman.",
    "The past.",
    "Catapults.",
    "A lifetime of sadness.",
    "Going an entire day without masturbating.",
    "Dwayne \"The Rock\" Johnson.",
    "A saxophone solo.",
    "A fart so powerful that it wakes the giants from their thousand-year slumber.",
    "My genitals.",
    "BATMAN!",
    "Preteens.",
    "More elephant cock than I bargained for.",
    "A micropenis.",
    "My ugly face and bad personality.",
    "A good sniff.",
    "Explaining how vaginas work.",
    "Genuine human connection.",
    "An old guy who's almost dead.",
    "Being a motherfucking sorcerer.",
    "Holding down a child and farting all over him.",
    "Land mines.",
    "Centaurs.",
    "My relationship status.",
    "Used panties.",
    "Alcoholism.",
    "Sexual peeing.",
    "A windmill full of corpses.",
    "Darth Vader.",
    "Daniel Radcliffe's delicious asshole.",
    "A good, strong gorilla.",
    "Nipple blades.",
    "Being able to talk to elephants.",
    "Making a pouty face.",
    "Drowning the kids in the bathtub.",
    "Emerging from the sea and rampaging through Tokyo.",
    "Magnets.",
    "Touching a pug right on his penis.",
    "Vladimir Putin.",
    "Spontaneous human combustion.",
    "Leprosy.",
    "Explosions.",
    "Licking things to claim them as your own.",
    "Consensual sex.",
    "Bananas.",
    "Masturbating.",
    "All the dues I've fucked.",
    "Running out of semen.",
    "Goblins.",
    "Laying an egg.",
    "A bowl of mayonnaise and human teeth.",
    "A micropig wearing a tiny raincoat and booties.",
    "A bitch slap.",
    "A man on the brink of orgasm.",
    "A much younger woman.",
    "A sad handjob.",
    "Police brutality.",
    "Throwing a virgin into a volcano.",
    "A sea of troubles.",
    "Multiple stab wounds.",
    "A tiny horse.",
    "Grandma.",
    "A bag of magic beans.",
    "Doing the right thing.",
    "Emma Watson.",
    "Racism.",
    "Powerful thighs.",
    "Men.",
    "Farting and walking away.",
    "German Chancellor Angela Merkel.",
    "Peeing a little bit.",
    "Viagra.&reg;",
    "Bisexuality.",
    "The clitoris.",
    "Soft, kissy missionary sex.",
    "Sitting on my face and telling me I'm garbage.",
    "Puberty.",
    "Poor people.",
    "Harry Potter erotica.",
    "Penis breath.",
    "Agriculture.",
    "The heart of a child.",
    "Justin Bieber.",
    "Concealing a boner.",
    "Not vaccinating my children because I am stupid.",
    "Sex with animals.",
    "Men discussing their feelings in an emotionally healthy way.",
    "Dead birds everywhere.",
    "My bright pink fuckhole.",
    "Having sex for the first time.",
    "An endless stream of diarrhea.",
    "Getting drugs off the street and into my body.",
    "German dungeon porn.",
    "Mouth herpes.",
    "Seeing what happens when you lock people in a room with hungry seagulls.",
    "72 virgins.",
    "Getting cummed on.",
    "Poor life choices.",
    "Being fat and stupid.",
    "Teaching a robot to love.",
    "Child abuse.",
    "Fucking my sister.",
    "Science.",
    "The gays.",
    "Becoming a blueberry.",
    "Oprah.",
    "Three dicks at the same time.",
    "Puppies!",
    "An unwanted pregnancy.",
    "The Holy Bible.",
    "Doing crimes.",
    "Having anuses for eyes.",
    "Silence.",
    "My balls on your face.",
    "Dead parents.",
    "Barack Obama.",
    "A snapping turtle biting the tip of your penis.",
    "African children.",
    "Fading away into nothingness.",
    "Spaghetti? Again?",
    "The miracle of childbirth.",
    "Selling crack to children.",
    "Menstrual rage.",
    "Still being a virgin.",
    "Shiny objects.",
    "Giving birth to the Antichrist.",
    "The placenta.",
    "Sunshine and rainbows.",
    "A little boy who won't shut the fuck up about dinosaurs.",
    "Finger painting.",
    "Natural selection.",
    "An erection that lasts longer than four hours.",
    "My soul.",
    "A middle-aged man on roller skates.",
    "Being a dick to children.",
    "Mutually assured destruction.",
    "The cool, refreshing taste of Pepsi.&reg;",
    "Nicolas Cage.",
    "Daddy issues.",
    "Accepting the way things are.",
    "The Big Bang.",
    "Inappropriate yodeling.",
    "An older woman who knows her way around the penis.",
    "Raptor attacks.",
    "The Patriarchy.",
    "Free samples.",
    "My ex-wife.",
    "The Pope.",
    "Covering myself with Parmesan cheese and chili flakes because I am pizza.",
    "White people.",
    "Unfathomable stupidity.",
    "A bird that shits human turds.",
    "Your weird brother.",
    "Jobs.",
    "Estrogen.",
    "Donald J. Trump.",
    "Casually suggesting a threesome.",
    "David Bowie flying in on a tiger made of lightning.",
    "Memes.",
    "A salty surprise.",
    "Balls.",
    "The Devil himself.",
    "Fucking the weatherman on live television.",
    "Necrophilia.",
    "Vomiting seafood and bleeding anally.",
    "Pulling out.",
    "Spectacular abs.",
    "Full frontal nudity.",
    "A tiny, gay guitar called a ukulele.",
    "Poorly-timed Holocaust jokes.",
    "Sweet, sweet vengeance.",
    "How amazing it is to be on mushrooms.",
    "Hope.",
    "The screams... the terrible screams.",
    "Gandhi.",
    "Getting fingered.",
    "Emotions.",
    "Wet dreams.",
    "Dark and mysterious forces beyond our control.",
    "Shaking a baby until it stops crying.",
    "Being on fire.",
    "Huge biceps.",
    "My vagina.",
    "My inner demons.",
    "Pooping in a laptop and closing it.",
    "A fetus.",
    "Strong female characters.",
    "Tentacle porn.",
    "The Jews.",
    "Teenage pregnancy.",
    "Saying \"I love you.\"",
    "50,000 volts straight to the nipples.",
    "Self-loathing.",
    "Erectile dysfunction.",
    "Poopy diapers.",
    "Friction.",
    "Oompa-Loompas.",
    "Drinking out of the toilet and eating garbage.",
    "Fragile masculinity.",
    "Kissing grandma on the forehead and turning off her life support.",
    "The true meaning of Christmas.",
    "A pyramid of severed heads.",
    "Getting really high.",
    "Hot cheese.",
    "Incest.",
    "Elderly Japanese men.",
    "Announcing that I am about to cum.",
    "Invading Poland.",
    "RoboCop.",
    "Flying sex snakes.",
    "Slaughtering innocent civilians.",
    "Establishing dominance.",
    "Girls.",
    "Italians.",
    "Jennifer Lawrence.",
    "Penis envy.",
    "Repression.",
    "Cards Against Humanity.",
    "Heartwarming orphans.",
    "A falcon with a cap on its head.",
    "AXE Body Spray.",
    "Solving problems with violence.",
    "Gloryholes.",
    "A homoerotic volleyball montage.",
    "Flightless birds.",
    "A disappointing birthday party.",
    "Permanent Orgasm-Face Disorder.",
    "The Blood of Christ.",
    "Cuddling.",
    "The American Dream.",
    "Pooping back and forth. Forever.",
    "The Force.",
    "Exactly what you'd expect.",
    "Getting crushed by a vending machine.",
    "A ball of earwax, semen, and toenail clippings.",
    "Diversity.",
    "Pixelated bukkake.",
    "Seeing Grandma naked.",
    "Women in yogurt commercials.",
    "Arnold Schwarzenegger.",
    "The bombing of Nagasaki.",
    "Chainsaws for hands.",
    "Fear itself.",
    "Ghosts.",
    "My neck, my back, my pussy, and my crack.",
    "God.",
    "Nazis.",
    "My collection of Japanese sex toys.",
    "One titty hanging out.",
    "How bad my daughter fucked up her dance recital.",
    "The violation of our most basic human rights.",
    "Morgan Freeman's voice.",
    "Stalin.",
    "Old-people smell.",
    "Fake tits.",
    "Sexual tension.",
    "A really cool hat.",
    "An octopus giving seven handjobs and smoking a cigarette.",
    "Listening to her problems without trying to solve them.",
    "The Russians.",
    "Murder.",
    "A crucifixion.",
    "Her Majesty, Queen Elizabeth II.",
    "Not wearing pants.",
    "Man meat.",
    "Many bats.",
    "Horse meat.",
    "Dick pics.",
    "One trillion dollars.",
    "Sperm whales.",
    "My sex life.",
    "Chemical weapons.",
    "Pictures of boobs.",
    "AIDS.",
    "Autocannibalism.",
    "A horde of Vikings.",
    "My abusive boyfriend who really isn't so bad once you get to know him.",
    "Fiery poops.",
    "Meth.",
    "Soup that is too hot.",
    "Stephen Hawking talking dirty.",
    "The milkman.",
    "Kanye West.",
    "Poverty.",
    "Judging everyone.",
    "PTSD.",
    "Bitches.",
    "The only gay person in a hundred kilometers.",
    "Wanking into a pool of children's tears.",
    "The Black Death.",
    "A brain tumour.",
    "Passive-aggressive Post-it notes.",
    "Amputees.",
    "Sniffing glue.",
    "Winking at old people.",
    "Americanization.",
    "Denying climate change.",
    "Chunks of dead backpacker.",
    "The inevitable heath death of the universe.",
    "An ass disaster.",
    "Disco fever.",
    "Words.",
    "Spending lots of money.",
    "Mooing.",
    "A cat video so cute that your eyes roll back and your spine slides out of your anus.",
    "Michael Jackson.",
    "Horrifying laser hair removal accidents.",
    "Dying alone and in pain.",
    "Shitting out a screaming face.",
    "Literally eating shit.",
    "A monkey smoking a cigar.",
    "Rich people.",
    "An evil man in evil clothes.",
    "A low standard of living.",
    "Wearing an octopus for a hat.",
    "Whining like a little bitch.",
    "Not having sex,",
    "A fat bald man from the Internet.",
    "Basic human decency.",
    "How awesome it is to be white.",
    "Nothing.",
    "Doing it in the butt.",
    "Moral ambiguity.",
    "Dining with cardboard cutouts of the cast of Friends.",
    "A big black dick.",
    "The arrival of pizza.",
    "An unstoppable wave of fire ants.",
    "Extremely tight jeans.",
    "A web of lies.",
    "Ominous background music.",
    "My machete.",
    "Multiple orgasms.",
    "Daddy's belt.",
    "Eating a hard boiled out of my husband's asshole.",
    "Friendly fire.",
    "The boners of the elderly.",
    "The hiccups.",
    "The crazy, ball-slapping sex your parents are having right now.",
    "Going around punching people.",
    "Letting everyone down.",
    "Nunchuck moves.",
    "The prunes I've been saving for you in my armpits.",
    "A PowerPoint presentation.",
    "The entire Internet.",
    "An AK-47.",
    "Walking in on Dad peeing into Mom's mouth.",
    "Dad's funny balls.",
    "Flying robots that kill people.",
    "Weapons-grade plutonium.",
    "Sexy pillow fights.",
    "Being white.",
    "A slightly shittier parallel universe.",
    "Having sex on top of a pizza.",
    "Power.",
    "Scrotum tickling.",
    "An army of skeletons.",
    "Actually getting shot, for real.",
    "A cop who is also a dog.",
    "A vagina that leads to another dimension.",
    "A man in yoga pants with a ponytail and feather earrings.",
    "Converting to Islam.",
    "Me.",
    "Tom Cruise.",
    "Intimacy problems.",
    "Leveling up.",
    "That ass.",
    "Kim Jong-un.",
    "The Dalai Lama.",
    "Ripping open a man's chest and pulling out his still-beating heart.",
    "A sad fat dragon with no friends.",
    "A surprising amount of hair.",
    "Some really fucked-up shit.",
    "Robert Downey Jr.",
    "Ryan Gosling riding in on a white horse.",
    "Sexual humiliation.",
    "Fisting.",
    "The human body.",
    "A defective condom.",
    "My father, who died when I was seven.",
    "The economy.",
    "Deflowering the princess.",
    "A Chinese tourist who wants something very badly but cannot communicate it.",
    "Graphic violence, adult language, and some sexual content.",
    "Self-flagellation.",
    "Shutting the fuck up.",
    "FIlling my son with spaghetti.",
    "The baby that ruined my pussy.",
    "Buying the right clothes to be cool.",
    "Being black.",
    "All of this blood.",
    "Edible underwear.",
    "An oversized lollipop,",
    "Stockholm Syndrome.",
    "The World of Warcraft.",
    "Grave robbing.",
    "Gandalf.",
    "Sneezing, farting, and cumming at the same time.",
    "Running naked through a mall, pissing and shitting everywhere.",
    "Blood farts.",
    "Panda sex.",
    "A thermonuclear detonation.",
    "Destroying the evidence.",
    "Vomiting mid-blowjob.",
    "A pi&ntilde;ata full of scorpions.",
    "Miley Cyrus.",
    "A Japanese toaster you can fuck.",
    "Suicidal thoughts.",
    "Grandpa's ashes.",
    "Reverse cowgirl.",
    "Keanu Reeves.",
    "LIving in a trashcan.",
    "My first kill.",
    "Mom.",
    "Children on leashes.",
    "Double penetration.",
    "Slave.",
    "White power.",
    "Indescribable loneliness.",
    "Tongue.",
    "Tiny nipples.",
    "Being fabulous.",
    "Homeless people.",
    "My cheating-son-of-a-bitch-husband.",
    "Screaming like a maniac.",
    "Heroin.",
    "Existing.",
    "The pirate's life.",
    "One Ring to rule them all.",
    "The flute.",
    "Being a busy adult with many important things to do.",
    "Slapping a racist old lady.",
    "Genetically engineered super-soldiers.",
    "Pumping out a baby every nine months.",
    "A mime having a stroke.",
    "Women voting.",
    "Gladiatorial combat.",
    "Some kind of bird man.",
    "Taking a man's eyes and balls out and putting his eyes where his balls go and then his balls in the eye holes.",
    "Mild autism.",
    "Rising from the grave.",
    "Not contributing to society in any meaningful way.",
    "Cock.",
    "Some douche with an acoustic guitar.",
    "Terrorists.",
    "Overpowering your father.",
    "Being a hideous beast that no one could love.",
    "Samuel L. Jackson.",
    "Making the penises kiss.",
    "Being a dinosaur.",
    "Staring at a painting and going \"hmmmmmmm...\"",
    "A sweet spaceships.",
    "Lady Gaga.",
    "Tripping balls.",
    "Eating an albino.",
    "Our first chimpanzee Prime Minister.",
    "Sudden Poop Explosion Disease.",
    "The total collapse of the global financial system.",
    "Loki, the trickster god.",
    "Making a friend.",
    "The Gulags.",
    "Hipsters.",
    "Wiping her butt.",
    "All my friends dying.",
    "The land of chocolate.",
    "Jesus.",
    "Another shot of morphine.",
    "Bosnian chicken farmers.",
    "How wet my pussy is.",
    "Having shotguns for legs.",
    "Bullshit.",
    "Blowing my boyfriend so hard so he shits.",
    "Cumming deep inside my best bro.",
    "Being awesome at sex.",
    "Santa Claus.",
    "Having a penis.",
    "Gay aliens."
]
