questions = [
    {"pick": 1, "text": "Next from J.K. Rowling: Harry Potter and the Chamber of ____."},
    {"pick": 1, "text": "What's there a ton of in heaven?"},
    {"pick": 1, "text": "It's a pity that kids these days are all getting involved with ____."},
    {"pick": 1, "text": "What's a girl's best friend?"},
    {"pick": 3, "text": "Make a haiku."},
    {"pick": 1, "text": "The class field trip was completely ruined by ____."},
    {"pick": 1, "text": "Uh, hey guys, I know this was my idea, but I'm having serious doubts about ____."},
    {"pick": 2, "text": "I never truly understood ____ until I encountered ____."},
    {"pick": 1, "text": "I'm sorry, Professor, but I couldn't complete my homework because of ____."},
    {"pick": 1, "text": "I drink to forget ____."},
    {"pick": 1, "text": "Hey Reddit! I'm ____. Ask me anything."},
    {"pick": 1, "text": "I got 99 problems but ____ ain't one."},
    {"pick": 1, "text": "Why can't I sleep at night?"},
    {"pick": 1, "text": "Dude, do not go in that bathroom. There's ____ in there."},
    {"pick": 1, "text": "Just once, I'd like to hear you say \"Thanks, Mom. Thanks for ____.\""},
    {"pick": 1, "text": "What made my first kiss so awkward?"},
    {"pick": 1, "text": "Just saw this upsetting video! Please retweet!! #stop____"},
    {"pick": 1, "text": "What never fails to liven up the party?"},
    {"pick": 1, "text": "What would grandma find disturbing, yet oddly charming?"},
    {"pick": 1, "text": "What's that sound?"},
    {"pick": 1, "text": "What will always get you laid?"},
    {"pick": 1, "text": "What ended my last relationship?"},
    {"pick": 1, "text": "Why do I hurt all over?"},
    {"pick": 1, "text": "But before I kill you, Mr. Bond, I must show you ____."},
    {"pick": 1, "text": "War! What is it good for?"},
    {"pick": 1, "text": "A romantic, candlelit dinner would be incomplete without ____."},
    {"pick": 1, "text": "Coming to Broadway this season, ____: The Musical."},
    {"pick": 2, "text": "And the Academy Award for ____ goes to ____."},
    {"pick": 1, "text": "Fun tip! When your man asks you to go down on him, try surprising him with ____ instead."},
    {"pick": 1, "text": "What gives me uncontrollable gas?"},
    {"pick": 2, "text": "For my next trick, I will pull ____ out of ____."},
    {"pick": 1, "text": "What's that smell?"},
    {"pick": 1, "text": "____. It's a trap!"},
    {"pick": 1, "text": "Well if you'll excuse me, gentlemen, I have a date with ____."},
    {"pick": 1, "text": "Why am I sticky?"},
    {"pick": 1, "text": "What makes life worth living?"},
    {"pick": 1, "text": "What's my secret power?"},
    {"pick": 1, "text": "What are my parents hiding from me?"},
    {"pick": 1, "text": "Daddy, why is mommy crying?"},
    {"pick": 1, "text": "During sex, I like to think about ____."},
    {"pick": 1, "text": "Mr. and Mrs. Diaz, we called you in because we're concerned about Cynthia. Are you aware that your daughter is ____?"},
    {"pick": 1, "text": "I'm no doctor, but I'm pretty sure what you're suffering from is called \"____.\""},
    {"pick": 1, "text": "Click Here for ____!!!"},
    {"pick": 1, "text": "What is Batman's guilty pleasure?"},
    {"pick": 1, "text": "The theme for next year's Eurovision Song Contest is \"We are ____.\""},
    {"pick": 2, "text": "In a world ravaged by ____, our only solace is ____."},
    {"pick": 1, "text": "What brought the orgy to a grinding halt?"},
    {"pick": 1, "text": "Lovin' you is easy 'cause you're ____."},
    {"pick": 1, "text": "Your persistence is admirable, my dear Prince. But you cannot win my heart with ____ alone."},
    {"pick": 1, "text": "The blind date was going horrible until we discovered our shared interest in ____."},
    {"pick": 1, "text": "Science will never explain ____."},
    {"pick": 1, "text": "The Five Stages of Grief: denial, anger, bargaining, ____, acceptance."},
    {"pick": 1, "text": "What has been making life difficult at the nudist colony?"},
    {"pick": 1, "text": "Charades was ruined for me forever when my mom had to act out ____."},
    {"pick": 1, "text": "Money can't buy me love, but it can buy me ____."},
    {"pick": 1, "text": "During his midlife crisis, my dad got really into ____."},
    {"pick": 2, "text": "When you get right down to it, ____ is just ____."},
    {"pick": 1, "text": "This is your captain speaking. Fasten your seatbelts and prepare for ____."},
    {"pick": 1, "text": "Tonight's top story: What you don't know about ____ could kills you."},
    {"pick": 1, "text": "Future historians will agree that ____ marked the beginning of America's decline."},
    {"pick": 1, "text": "Coming this season, Samuel Beckett's classic existential play: Waiting for ____."},
    {"pick": 1, "text": "When I pooped, what came out of my butt?"},
    {"pick": 1, "text": "A successful job interview begins with a firm handshake and ends with ____."},
    {"pick": 1, "text": "Finally! A service that delivers ____ right to your door."},
    {"pick": 1, "text": "And what did you bring for show and tell?"},
    {"pick": 1, "text": "When I am a billionaire, I shall erect a 20-meter statue to commemorate ____."},
    {"pick": 1, "text": "When all else fails, I can always masturbate to ____."},
    {"pick": 2, "text": "I spent my whole life working toward ____, only to have it ruined by ____."},
    {"pick": 2, "text": "____ would be woefully incomplete without ____."},
    {"pick": 1, "text": "Next on Eurosport: The World Championship of ____."},
    {"pick": 1, "text": "In his new self-produced album, Kanye West raps over the sounds of ____."},
    {"pick": 1, "text": "In Rome, there are whisperings that the Vatican has a secret room devoted to ____."},
    {"pick": 2, "text": "Having problems with ____? Try ____!"},
    {"pick": 1, "text": "The secret to a lasting marriage is communication, communication, and ____."},
    {"pick": 2, "text": "My mom freaked out when she looked at my browser history and found ____.com/____."},
    {"pick": 1, "text": "In the seventh circle of Hell, sinners must endure ____ for all eternity."},
    {"pick": 1, "text": "____. Awesome in theory, kind of a mess in practice."},
    {"pick": 1, "text": "My plan for world domination begins with ____."},
    {"pick": 1, "text": "I learned the hard way that you can't cheer up a grieving friend with ____."},
    {"pick": 1, "text": "A remarkable new study shows that chimps have evolved their own primitive version of ____."},
    {"pick": 2, "text": "After months of practice with ____, I think I'm finally ready for ____."},
    {"pick": 1, "text": "When I am Prime Minister, I will create the Ministry of ____."},
    {"pick": 1, "text": "Turns out that ____-Man was neither the hero we needed nor wanted."},
    {"pick": 2, "text": "With enough time and pressure, ____ will turn into ____."},
    {"pick": 1, "text": "What left this stain on my couch?"},
    {"pick": 2, "text": "Dear Sir or Madam, We regret to inform you that the Office of ____ has denied your request for ____."},
    {"pick": 1, "text": "I'm not like the rest of you. I'm too rich and busy for ____."},
    {"pick": 1, "text": "The healing process began when I joined a support group for victims of ____."},
    {"pick": 1, "text": "Doctor, you've gone too far! The human body wasn't meant to withstand that amount of ____!"},
    {"pick": 1, "text": "Only two things in life are certain: death and ____."}
]
