questions = [
    "Next from J.K. Rowling: <i>Harry Potter and the Chamber of ____.</i>",
    "What's there a ton of in heaven?",
    "It's a pity that kids these days are all getting involved with ____.",
    "What's a girl's best friend?",
    "The class field trip was completely ruined by ____.",
    "Uh, hey guys, I know this was my idea, but I'm having serious doubts about ____.",
    "I'm sorry, Professor, but I couldn't complete my homework because of ____.",
    "I drink to forget ____.",
    "Hey Reddit! I'm ____. Ask me anything.",
    "I got 99 problems but ____ ain't one.",
    "Why can't I sleep at night?",
    "Dude, <i>do not</i> go in that bathroom. There's ____ in there.",
    "Just once, I'd like to hear you say \"Thanks, Mom. Thanks for ____.\"",
    "What made my first kiss so awkward?",
    "Just saw this upsetting video! Please retweet!! #stop____",
    "What never fails to liven up the party?",
    "What would grandma find disturbing, yet oddly charming?",
    "What's that sound?",
    "What will always get you laid?",
    "What ended my last relationship?",
    "Why do I hurt all over?",
    "But before I kill you, Mr. Bond, I must show you ____.",
    "War! What is it good for?",
    "A romantic, candlelit dinner would be incomplete without ____.",
    "Coming to Broadway this season, ____: The Musical.",
    "Fun tip! When your man asks you to go down on him, try surprising him with ____ instead.",
    "What gives me uncontrollable gas?",
    "What's that smell?",
    "____. It's a trap!",
    "Well if you'll excuse me, gentlemen, I have a date with ____."
]
