white_cards = [
    "Throwing grapes at a man until he loses touch with reality.",
    "A stray pube.",
    "Facebook.",
    "Pac-Man uncontrollably guzzling cum.",
    "An Oedipus complex.",
    "Scientology.",
    "My fat daughter.",
    "Having big dreams but no realistic way to achieve them.",
    "A time travel paradox.",
    "Lactation.",
    "Dick fingers.",
    "Dying.",
    "My good bra.",
    "Me time.",
    "Seeing my father cry.",
    "Hot people.",
    "Dead babies.",
    "Not reciprocating oral sex.",
    "A bleached asshole.",
    "Flesh-eating bacteria.",
    "Itchy pussy.",
    "Foreskin.",
    "How far I can get my own penis up my butt.",
    "World peace.",
    "Expecting a burp and vomiting on the floor.",
    "Kamikaze pilots.",
    "Being rich.",
    "Shapeshifters.",
    "Breaking out into song and dance.",
    "Pretending to care.",
    "Waiting till marriage.",
    "The wifi password.",
    "Being a woman.",
    "The past.",
    "Catapults.",
    "A lifetime of sadness.",
    "Going an entire day without masturbating.",
    "Dwayne \"The Rock\" Johnson.",
    "A saxophone solo.",
    "A fart so powerful that it wakes the giants from their thousand-year slumber.",
    "My genitals.",
    "BATMAN!",
    "Preteens.",
    "More elephant cock than I bargained for.",
    "A micropenis.",
    "My ugly face and bad personality.",
    "A good sniff.",
    "Explaining how vaginas work.",
    "Genuine human connection.",
    "An old guy who's almost dead.",
    "Being a motherfucking sorcerer.",
    "Holding down a child and farting all over him.",
    "Land mines.",
    "Centaurs.",
    "My relationship status.",
    "Used panties.",
    "Alcoholism.",
    "Sexual peeing.",
    "A windmill full of corpses.",
    "Darth Vader."
]
